name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.139.4"  # Specify your desired Hugo version here

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Hugo CLI
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.tar.gz
        tar -xzf hugo_extended_0.139.4_linux-amd64.tar.gz
        sudo mv hugo /usr/local/bin/

    - name: Build
      run: |
        hugo
        echo "atharvawaranashiwar.me" > public/CNAME 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}  # It's safer to use GITHUB_TOKEN which is automatically provided
        publish_dir: ./public
        publish_branch: gh-pages  # Ensure this is your GitHub Pages branch
        keep_files: true  # Set to false to allow a clean deployment each time
