name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.139.4"  # Specify your desired Hugo version here

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Hugo CLI
      run: |
        wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.deb \
        && sudo dpkg -i hugo.deb

    - name: Build
      run: hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # It's safer to use GITHUB_TOKEN which is automatically provided
        publish_dir: ./public
        publish_branch: gh-pages  # Ensure this is your GitHub Pages branch
        keep_files: false  # Set to false to allow a clean deployment each time
